# Generated by Django 5.1.5 on 2025-01-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0, verbose_name='점수'),
        ),
    ]
