# Generated by Django 5.1.5 on 2025-01-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Attack',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
