# Generated by Django 5.1.5 on 2025-01-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='attacker_card',
        ),
        migrations.RemoveField(
            model_name='board',
            name='defender_card',
        ),
        migrations.RemoveField(
            model_name='board',
            name='attacker_card_number',
        ),
        migrations.RemoveField(
            model_name='board',
            name='defender_card_number',
        ),
        migrations.AlterField(
            model_name='board',
            name='howTowin',
            field=models.CharField(choices=[('L', 'Low'), ('H', 'High'), ('무', '무승부')], max_length=1, verbose_name='승리조건'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
